----- CRASH SUMMARY @ 20250916T082156 -----
[HEAD api.err]
Traceback (most recent call last):
  File "/home/youjie/projects/smart-mail-agent-ssot-pro/tools/api_server.py", line 28, in <module>
    print(f"[API] http://127.0.0.1:{port}"); HTTPServer(("127.0.0.1", port), H).serve_forever()
  File "/usr/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.10/http/server.py", line 137, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
[TAIL server.log]
[TAIL run.log]
[PICK] api_server = tools/api_server.py
[DEEPDOCTOR ERR] ec=1
[TAIL py_last_trace.txt]
[TAIL api.out]
[API] http://127.0.0.1:8088
