[*] PACK start @ 20250916T013022
[*] OUT_DIR = /home/youjie/projects/smart-mail-agent-ssot-pro/reports_auto/export/20250916T013022
[*] ERR_DIR = /home/youjie/projects/smart-mail-agent-ssot-pro/reports_auto/ERR
[*] LIMITS  = part<=256m, parts<=10, pointer>10485760B
[*] PATHS:
  MODEL = /home/youjie/projects/smart-mail-agent-ssot-pro/intent/intent/artifacts/intent_pro_cal.pkl
  RULES = /home/youjie/projects/smart-mail-agent-ssot-pro/intent/intent/.sma_tools/runtime_threshold_router.py
  DATA  = /home/youjie/projects/smart-mail-agent-ssot-pro/data/intent_eval/dataset.cleaned.jsonl
Traceback (most recent call last):
  File "<stdin>", line 34, in <module>
  File "/usr/lib/python3.10/pathlib.py", line 1154, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
FileNotFoundError: [Errno 2] No such file or directory: '/home/youjie/projects/smart-mail-agent-ssot-pro/reports_auto/export/20250916T013022/meta/MANIFEST.json'
[ERR] pack failed. LOG=/home/youjie/projects/smart-mail-agent-ssot-pro/reports_auto/export/20250916T013022/pack.log  ERR=/home/youjie/projects/smart-mail-agent-ssot-pro/reports_auto/export/20250916T013022/pack.err
[ERR] pack failed. LOG=/home/youjie/projects/smart-mail-agent-ssot-pro/reports_auto/export/20250916T013022/pack.log  ERR=/home/youjie/projects/smart-mail-agent-ssot-pro/reports_auto/export/20250916T013022/pack.err
